Repository muruga21/LoadDistrix, pull requests merged in 2024-10, with the labels that each got.

#2 #Add Code_Of_Conduct.md
  Code_Of_Conduct.md
Labels: good first issue, gssoc, gssoc-ext, level1

#4 #Add Github Greetings (level1) enhancement
  .github/workflows/greetings.yml
Labels: gssoc, gssoc-ext, level1

#6 Added new feature: dynamic config file
  README.md
  go.mod
  go.sum
  lib/config.go
  main.go
Labels: gssoc, gssoc-ext, hacktoberfest

#7 Update README.md
  README.md
Labels: gssoc, gssoc-ext, level1, hacktoberfest

#9 Implement graceful shutdown for the load balancer server
  main.go
Labels: gssoc, gssoc-ext, hacktoberfest, hackoctoberfest-accepted, level3

#12 Updated README.md
  README.md
Labels: gssoc, gssoc-ext, level1, hacktoberfest, hackoctoberfest-accepted
